name: CI
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
env:
  ACTIONS_RUNNER_DEBUG: true
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
#        os: [ windows-latest, ubuntu-latest, macos-latest ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Fetch all history for all tags and branches
        run: |
          git fetch --prune --unshallow
      - run: |
          npm install
          npm run format-check
          npm run build:agent:github
        name: Build code
      - name: gitversion/setup
        uses: ./gitversion/setup
        with:
          versionSpec: '5.x'
      - name: gitversion/execute
        id: gitversion # step id used as reference for output values
        uses: ./gitversion/execute
      - run: |
          echo "FullSemVer (env.fullSemVer)                                 : ${{ env.fullSemVer }}"
          echo "FullSemVer (env.GitVersion_FullSemVer)                      : ${{ env.GitVersion_FullSemVer }}"
          echo "FullSemVer (steps.gitversion.outputs.fullSemVer)            : ${{ steps.gitversion.outputs.fullSemVer }}"
          echo "FullSemVer (steps.gitversion.outputs.GitVersion_FullSemVer) : ${{ steps.gitversion.outputs.GitVersion_FullSemVer }}"
        name: Use variables and output